CREATE TABLE TASK(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
DESCRIPTION VARCHAR(255),
STATUS BIGINT,
ASSIGNE BIGINT,
PRIORITY BIGINT
);

CREATE TABLE USERS(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(255)
);

CREATE TABLE PRIORITY(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(255)
);

CREATE TABLE STATUS(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(255)
);